# Site settings

title: Elm Community

description: > # this means to ignore newlines until "baseurl:"
  Unofficial group for shared work on Elm packages and documentation

github_username:  elm-community

# Build settings

markdown: kramdown

# The following are supposed to be defaults per
# https://help.github.com/articles/using-jekyll-with-pages/ but as of 2016-02-02
# I have to set them explicitly for correct output. -@fredcy
kramdown:
  input: GFM
  hard_wrap: false
  
